"""
update_metrics.py — Auto-Update Training Metrics in index.html
==============================================================
PURPOSE : After running evaluate.py, run this script to push the latest
          PSNR/SSIM numbers into the Training Metrics tab in index.html.

SHARED CODE:
          Imports find_latest() from utils.py for checkpoint detection.

TWO MODES:
  Auto   — reads metrics from eval_report/ JSON files (run evaluate.py first)
  Manual — pass numbers as command-line arguments (fastest after Kaggle sessions)

TRAINING COMPLETION TARGETS:
    GAN    : 200 epochs
    ResNet : 100 epochs

HOW TO USE:
    # Auto mode
    python update_metrics.py

    # Manual mode (fastest — use your final evaluated scores)
    python update_metrics.py --psnr-gan 22.41 --ssim-gan 0.8909 \\
                             --psnr-resnet 22.49 --ssim-resnet 0.8929 \\
                             --psnr-opencv 21.18 --ssim-opencv 0.8861
"""

# ── Standard library ───────────────────────────────────────────────────────────
import re        # regex for finding/replacing values in HTML
import sys       # sys.exit on error
import json      # reading eval JSON files
import argparse

# ── File handling ──────────────────────────────────────────────────────────────
from pathlib import Path

# ── Shared utility: checkpoint epoch detection ─────────────────────────────────
from colorize_utils import find_latest   # find highest-epoch .pth file matching a pattern


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 1 — COMMAND-LINE ARGUMENTS
# ══════════════════════════════════════════════════════════════════════════════

parser = argparse.ArgumentParser(
    description="Update Training Metrics tab in index.html"
)
parser.add_argument("--psnr-gan",    type=float, default=None, help="GAN avg PSNR (e.g. 22.41)")
parser.add_argument("--ssim-gan",    type=float, default=None, help="GAN avg SSIM (e.g. 0.8909)")
parser.add_argument("--psnr-resnet", type=float, default=None, help="ResNet avg PSNR")
parser.add_argument("--ssim-resnet", type=float, default=None, help="ResNet avg SSIM")
parser.add_argument("--psnr-opencv", type=float, default=None, help="OpenCV avg PSNR")
parser.add_argument("--ssim-opencv", type=float, default=None, help="OpenCV avg SSIM")
parser.add_argument("--html",        default="index.html",     help="Path to index.html")
args = parser.parse_args()


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 2 — DETECT CHECKPOINT EPOCH COUNTS (using utils.find_latest)
# ══════════════════════════════════════════════════════════════════════════════

# find_latest() from utils.py — returns str path or None
gan_ckpt    = find_latest("generator_epoch*.pth")
resnet_ckpt = find_latest("generator_resnet_epoch*.pth")

# Extract epoch number from filename (e.g. "generator_epoch200" → 200)
gan_epoch    = int("".join(filter(str.isdigit, Path(gan_ckpt).stem)))    if gan_ckpt    else 0
resnet_epoch = int("".join(filter(str.isdigit, Path(resnet_ckpt).stem))) if resnet_ckpt else 0

print("=" * 58)
print("  update_metrics.py — Training Metrics Updater")
print("=" * 58)
print(f"  GAN    : {gan_ckpt    or 'not found'}  → epoch {gan_epoch}")
print(f"  ResNet : {resnet_ckpt or 'not found'}  → epoch {resnet_epoch}")
print("=" * 58)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 3 — READ METRICS FROM JSON FILES (generated by evaluate.py)
# ══════════════════════════════════════════════════════════════════════════════

def read_json(label_pattern, exclude=None):
    """
    Read avg_psnr and avg_ssim from an eval_report/ JSON file.

    label_pattern — substring that must appear in the JSON filename
    exclude       — substring that must NOT appear (GAN uses exclude='resnet'
                    to avoid reading ResNet's JSON file by mistake)

    Returns: (avg_psnr, avg_ssim) or (None, None) if no file found.
    """
    jsons = list(Path("eval_report").glob(f"metrics_*{label_pattern}*.json"))
    if exclude:
        jsons = [j for j in jsons if exclude not in j.name]
    if not jsons:
        return None, None
    try:
        jsons = sorted(jsons, key=lambda p: p.name)
        data  = json.loads(jsons[-1].read_text())
        print(f"  Reading from: {jsons[-1].name}")
        return data.get("avg_psnr"), data.get("avg_ssim")
    except Exception:
        return None, None


# Priority: CLI argument → JSON file → leave HTML unchanged
# exclude='resnet' for GAN is critical — prevents reading ResNet JSON as GAN
gan_psnr    = args.psnr_gan    or read_json("epoch", exclude="resnet")[0]
gan_ssim    = args.ssim_gan    or read_json("epoch", exclude="resnet")[1]
resnet_psnr = args.psnr_resnet or read_json("resnet")[0]
resnet_ssim = args.ssim_resnet or read_json("resnet")[1]
opencv_psnr = args.psnr_opencv or read_json("OpenCV")[0]
opencv_ssim = args.ssim_opencv or read_json("OpenCV")[1]

print(f"  GAN    PSNR={gan_psnr}  SSIM={gan_ssim}")
print(f"  ResNet PSNR={resnet_psnr}  SSIM={resnet_ssim}")
print(f"  OpenCV PSNR={opencv_psnr}  SSIM={opencv_ssim}")
print("=" * 58)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 4 — COLOUR AND STATUS HELPERS
# ══════════════════════════════════════════════════════════════════════════════

def psnr_color(v):
    """
    CSS variable for PSNR quality:
      >= 22 dB → green  (good colourization)
      >= 20 dB → gold   (acceptable)
      < 20 dB  → red    (poor)
    """
    if v is None: return "var(--accent2)"   # blue: no data yet
    return "var(--green)" if v >= 22 else "var(--gold)" if v >= 20 else "var(--red)"


def epoch_color(ep, target):
    """Green if training complete (ep >= target), else blue (ongoing)."""
    return "var(--green)" if ep >= target else "var(--accent2)"


gan_done    = gan_epoch    >= 200   # GAN target: 200 epochs
resnet_done = resnet_epoch >= 100   # ResNet target: 100 epochs


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 5 — LOAD INDEX.HTML
# ══════════════════════════════════════════════════════════════════════════════

html_path = Path(args.html)
if not html_path.exists():
    print(f"❌ {html_path} not found!")
    sys.exit(1)

with open(html_path, "r", encoding="utf-8") as f:
    html = f.read()

original = html   # save original to detect if anything changed


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 6 — HTML REPLACEMENT HELPER
# ══════════════════════════════════════════════════════════════════════════════

def replace_bigval(html, label_text, new_val, new_color, new_hint):
    """
    Find a 'big metric card' by its label and update: value, colour, hint text.

    Expected HTML structure:
      <div class="big-val" style="color:...">VALUE</div>
      <div class="big-label">LABEL_TEXT</div>
      <div class="big-hint">HINT</div>
    """
    pattern = (
        r'(<div class="big-val"[^>]*>)[^<]*(</div>\s*'
        r'<div class="big-label">' + re.escape(label_text) + r'</div>\s*'
        r'<div class="big-hint">)[^<]*(</div>)'
    )
    replacement = f'<div class="big-val" style="color:{new_color}">{new_val}\\2{new_hint}\\3'
    new_html    = re.sub(pattern, replacement, html, flags=re.DOTALL)
    if new_html == html:
        print(f'  ⚠️  Card not found: "{label_text}" — skipping')
    return new_html


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 7 — UPDATE METRIC CARDS
# ══════════════════════════════════════════════════════════════════════════════

if gan_psnr:
    html = replace_bigval(html, "GAN PSNR (dB)", f"{gan_psnr:.2f}", psnr_color(gan_psnr),
                          f'epoch {gan_epoch} · {"complete ✓" if gan_done else "ongoing → 200"}')

if resnet_psnr:
    html = replace_bigval(html, "ResNet PSNR (dB)", f"{resnet_psnr:.2f}", psnr_color(resnet_psnr),
                          f'epoch {resnet_epoch} · {"complete ✓" if resnet_done else "ongoing → 100"}')

html = replace_bigval(html, "GAN Epochs", str(gan_epoch), epoch_color(gan_epoch, 200),
                      "two-phase · complete ✓" if gan_done else f"phase 2 · {gan_epoch}/200")

html = replace_bigval(html, "ResNet Epochs", str(resnet_epoch), epoch_color(resnet_epoch, 100),
                      "pretrained · complete ✓" if resnet_done else f"pretrained · ongoing → 100")

if opencv_psnr and "OpenCV PSNR" in html:
    html = replace_bigval(html, "OpenCV PSNR (dB)", f"{opencv_psnr:.2f}",
                          psnr_color(opencv_psnr), "Zhang 2016 · pretrained")


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 8 — UPDATE OTHER DYNAMIC SECTIONS
# ══════════════════════════════════════════════════════════════════════════════

# ResNet phase detail line
html = re.sub(
    r'<div class="phase-detail">\d+ / \d+ epochs · ResNet34 pretrained encoder</div>',
    f'<div class="phase-detail">{resnet_epoch} / 100 epochs · ResNet34 pretrained encoder</div>',
    html
)

# ResNet phase result line with comparison note
if resnet_psnr and resnet_ssim:
    if gan_psnr and resnet_psnr >= gan_psnr and gan_ssim and resnet_ssim >= gan_ssim:
        note = "ResNet leading both ✓"
    elif gan_psnr and resnet_psnr >= gan_psnr:
        note = "ResNet leading PSNR ✓"
    elif gan_ssim and resnet_ssim >= gan_ssim:
        note = "ResNet leading SSIM ✓"
    else:
        note = "GAN still leading"
    html = re.sub(
        r'<div class="phase-result">(?:Epoch \d+:|Final:)[^<]+</div>',
        f'<div class="phase-result">Epoch {resnet_epoch}: PSNR {resnet_psnr:.2f} dB · '
        f'SSIM {resnet_ssim:.4f} · {note}</div>',
        html
    )

# Update phase badge once ResNet training is complete
if resnet_done:
    html = re.sub(
        r'<div class="phase-badge active">Training → ep\.\d+</div>',
        f'<div class="phase-badge done">Done · ep.{resnet_epoch}</div>',
        html
    )

# Update all inline "ResNet ep.XX" mentions
html = re.sub(r"ResNet ep\.\d+", f"ResNet ep.{resnet_epoch}", html)

# Add OpenCV row to architecture table if missing
if opencv_psnr and "OpenCV CNN" not in html:
    html = html.replace(
        '<div class="arch-row"><span class="arch-k">ResNet Generator</span>',
        ('<div class="arch-row"><span class="arch-k">OpenCV CNN</span>'
         '<span class="arch-v">Zhang et al. 2016 · pretrained on ImageNet</span></div>\n'
         '            <div class="arch-row"><span class="arch-k">ResNet Generator</span>')
    )


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 9 — SAVE UPDATED HTML
# ══════════════════════════════════════════════════════════════════════════════

if html == original:
    print("\n⚠️  No changes made — metrics may already be up to date.")
    print("    If unexpected: check index.html has big-val/big-label/big-hint elements.")
else:
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html)
    print("\n✅ index.html updated successfully!")
    print(f"  GAN    → ep.{gan_epoch}  PSNR {gan_psnr or '—'}  SSIM {gan_ssim or '—'}")
    print(f"  ResNet → ep.{resnet_epoch}  PSNR {resnet_psnr or '—'}  SSIM {resnet_ssim or '—'}")
    if opencv_psnr:
        print(f"  OpenCV → pretrained    PSNR {opencv_psnr}  SSIM {opencv_ssim}")
print()
